name: Release Workflow

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.get_tag.outputs.new_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Generate new tag
        id: get_tag
        run: |
          latest=$(git tag --sort=-v:refname | head -n 1)
          echo "Latest tag: $latest"
          if [[ -z "$latest" ]]; then
            new_tag="1.0.0"
          else
            version=${latest#v}
            major=$(echo "$version" | cut -d. -f1)
            minor=$(echo "$version" | cut -d. -f2)
            patch=$(echo "$version" | cut -d. -f3)
            patch=$((patch + 1))
            new_tag="$major.$minor.$patch"
          fi
          echo "new_tag=$new_tag" >> "$GITHUB_OUTPUT"

      - name: Create and push tag
        run: |
          git tag ${{ steps.get_tag.outputs.new_tag }}
          git push origin ${{ steps.get_tag.outputs.new_tag }}

  build-docker:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: tag

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build
        env:
          CI_USERNAME: ${{ secrets.CI_USERNAME }}
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
        run: |
          owner="${{ github.repository_owner }}"
          lower_owner="${owner,,}"
          mvn compile jib:build -DskipTests -Djib.to.image=ghcr.io/${lower_owner}/products-api:${{ needs.tag.outputs.new_tag }}

  prod_deploy:
    runs-on: ubuntu-latest
    needs: [build-docker, tag]

    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v3
        with:
          repository: PayeTonKawa2025/infra-gitops
          token: ${{ secrets.CI_TOKEN }}
          path: gitops

      - name: Update file with tag
        run: |
          cd gitops
          yq -i '
            .spec.source.helm.values |= (
              from_yaml
                | .image.tag = "${{ needs.tag.outputs.new_tag }}"
              | to_yaml
          )' apps/payetonkawa/products-api.yaml
          cat apps/payetonkawa/products-api.yaml
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add apps/payetonkawa/products-api.yaml
          git commit -m "feat(products-api): deploy ${{ needs.tag.outputs.new_tag }}"
          git push origin main
